# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Driver' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Driver
  pod 'Alamofire'
  pod 'SwiftLocation'
  pod 'SwiftyJSON'
  pod 'SwiftyTimer'
   pod 'Presentr'
   
  target 'DriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DriverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
